###
### Special magic GitHub labels
### https://help.github.com/en/github/building-a-strong-community/encouraging-helpful-contributions-to-your-project-with-labels
#
- name: "good first issue"
  color: 7057ff
  description: "Good for newcomers"
- name: "hacktoberfest"
  color: ff8c00
  description: "Help wanted" 

###
### Areas
#
- name: ux
  color: 00A4E0
  description: "Area: UX"
- name: docs
  color: 13B9F5
  description: "Area: Documentation"
- name: testing
  color: 15BBF7
  description: "Area: Testing"
- name: monitoring
  color: 0E8A16
  description: "Area: Monitoring"

###
### Kinds
#
- name: bug
  color: c92712
  description: "Kind: Bug"
- name: feature
  color: FFF3B8
  description: "Kind: Feature / Enhancement"
- name: refactoring
  color: FFFABF
  description: "Kind: Refactoring / Cleanup"

###
### Statuses
#
- name: blocked
  color: C78D80
  description: "Status: Blocked"
- name: wont-fix
  color: 6D3326
  description: "Status: Won't fix"
