version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - skip-initialism-name-checks: true
                upper-case-const: true
                skip-package-name-checks: true
                skip-package-name-collision-with-go-std: true
                extra-bad-package-names:
                  - helpers
                  - models
                  - util # we sadly use it
                  - http # we sadly use it
                  - errors # we sadly use it
                  - common # we sadly use it
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - cyclop
          - depguard
          - errcheck
          - forbidigo
          - goconst
          - gocyclo
          - gosec
          - lll
          - mnd
          - nilnil
          - noctx
          - revive
        path: _test\.go
      - path: _test\.go
        text: SA1019
      - linters:
          - lll
        path: protobuf/gen.go
        source: '^//go:generate '
      - linters:
          - forbidigo
        path: cmd
      - linters:
          - forbidigo
        path: internal/lib
      - linters:
          - forbidigo
          - goconst
        path: internal/drand-cli
      - linters:
          - revive
        path: internal/metrics/threshold_monitor_test.go
      - linters:
          - dupl
        path: crypto/schemes.go
      - linters:
          - nilnil
        path: internal/core/drand_proxy.go
      - path: internal/core/drand_proxy.go
        text: SA1019
      - linters:
          - gosec
        text: G115
    paths:
      - demo
      - test
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/drand
  exclusions:
    generated: lax
    paths:
      - demo
      - test
      - third_party$
      - builtin$
      - examples$
