# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- main: ./cmd/drand/drand.go
  env:
  - CGO_ENABLED=0
  ldflags:
     - -s -w -X github.com/drand/drand/v2/internal/drand-cli.buildDate={{.Date}} -X github.com/drand/drand/v2/internal/drand-cli.gitCommit={{.ShortCommit}}
  mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
