version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine3.16
    environment:
      - POSTGRES_USER=drand
      - POSTGRES_PASSWORD=drand
      - POSTGRES_DB=drand
    ports:
      - 35432:5432
