FROM alpine

MAINTAINER Nicolas Gailly <nicolas.gailly@epfl.ch>

RUN apk update 
RUN apk add --no-cache bash \
            git \
            make \
            clang \
            llvm \
            gmp \
            gmp-dev \
            libgmpxx  \
            libstdc++ \
            g++ \
            openssl \
            openssl-dev \ 
            go

RUN git clone https://github.com/dfinity/bn /bn
WORKDIR /bn
RUN make install && make
WORKDIR /
RUN rm -rf /bn && mkdir -p /go/src
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
