// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto/vss/vss.proto

package vss // import "github.com/drand/drand/protobuf/crypto/vss"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import crypto "github.com/drand/drand/protobuf/crypto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EncryptedDeal holds a share encrypted towards the share holder's longterm
// public key..
type EncryptedDeal struct {
	// ephemereal diffie hellman key
	Dhkey []byte `protobuf:"bytes,1,opt,name=dhkey,proto3" json:"dhkey,omitempty"`
	// schnorr signature over the dhkey by the longterm key of the dealer
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// nonce used in the generation of the ephemereal key
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// cipher of the deal marshalled by protobuf2. TODO: marshal in a
	// more explicit and easier way.
	Cipher               []byte   `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedDeal) Reset()         { *m = EncryptedDeal{} }
func (m *EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*EncryptedDeal) ProtoMessage()    {}
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_vss_e8498a9ffaf39581, []int{0}
}
func (m *EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedDeal.Unmarshal(m, b)
}
func (m *EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedDeal.Marshal(b, m, deterministic)
}
func (dst *EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedDeal.Merge(dst, src)
}
func (m *EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_EncryptedDeal.Size(m)
}
func (m *EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedDeal proto.InternalMessageInfo

func (m *EncryptedDeal) GetDhkey() []byte {
	if m != nil {
		return m.Dhkey
	}
	return nil
}

func (m *EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

//
// Deal holds the share created by a dealer for a round of a vss or dkg protocol
// It is always meant to be encrypted when on transit because it contains
// private information (the share).
type Deal struct {
	// session id of the current protocol run
	SessionId []byte `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// private share of the deal
	Share *crypto.PrivateShare `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	// threshold of the secret sharing protocol run
	Threshold uint32 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// commitments of the polynomial used to derive the share
	Commitments          [][]byte `protobuf:"bytes,4,rep,name=commitments,proto3" json:"commitments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_vss_e8498a9ffaf39581, []int{1}
}
func (m *Deal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deal.Unmarshal(m, b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
}
func (dst *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(dst, src)
}
func (m *Deal) XXX_Size() int {
	return xxx_messageInfo_Deal.Size(m)
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *Deal) GetShare() *crypto.PrivateShare {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *Deal) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Deal) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

//
// Response is the response of a participant after having received an encrypted
// deal. It is meant to be broadcasted to every participants.
type Response struct {
	// session id of the
	SessionId []byte `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// index of the verifier issuing the response
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// status of the response. false = complaint, true = approval
	Status bool `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// signature over the packet using the longterm's key of the participant at
	// the given index
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_vss_e8498a9ffaf39581, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

//
// Justification enables a dealer to justify that it did not cheat in case some
// nodes complain about their received deal. It is NOT YET in production use
// though.
type Justification struct {
	// session id of the current run
	SessionId []byte `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// index of the issuer of this justification
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// plaintext deal that the complaint response points to
	Deal *Deal `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal,omitempty"`
	// signature over the whole packet
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Justification) Reset()         { *m = Justification{} }
func (m *Justification) String() string { return proto.CompactTextString(m) }
func (*Justification) ProtoMessage()    {}
func (*Justification) Descriptor() ([]byte, []int) {
	return fileDescriptor_vss_e8498a9ffaf39581, []int{3}
}
func (m *Justification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Justification.Unmarshal(m, b)
}
func (m *Justification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Justification.Marshal(b, m, deterministic)
}
func (dst *Justification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Justification.Merge(dst, src)
}
func (m *Justification) XXX_Size() int {
	return xxx_messageInfo_Justification.Size(m)
}
func (m *Justification) XXX_DiscardUnknown() {
	xxx_messageInfo_Justification.DiscardUnknown(m)
}

var xxx_messageInfo_Justification proto.InternalMessageInfo

func (m *Justification) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *Justification) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Justification) GetDeal() *Deal {
	if m != nil {
		return m.Deal
	}
	return nil
}

func (m *Justification) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedDeal)(nil), "vss.EncryptedDeal")
	proto.RegisterType((*Deal)(nil), "vss.Deal")
	proto.RegisterType((*Response)(nil), "vss.Response")
	proto.RegisterType((*Justification)(nil), "vss.Justification")
}

func init() { proto.RegisterFile("crypto/vss/vss.proto", fileDescriptor_vss_e8498a9ffaf39581) }

var fileDescriptor_vss_e8498a9ffaf39581 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xeb, 0xc6, 0x96, 0xad, 0x97, 0x3a, 0xa4, 0x88, 0x83, 0xd1, 0xd3, 0x14, 0x69,
	0x61, 0x7e, 0x03, 0xd1, 0x83, 0x9e, 0x24, 0xde, 0xbc, 0x48, 0xd6, 0xbc, 0xad, 0xc1, 0x35, 0xa9,
	0x79, 0xe9, 0x70, 0x47, 0xbf, 0x81, 0x1f, 0x59, 0xf2, 0x5a, 0x98, 0x7a, 0x50, 0xf0, 0x90, 0xc3,
	0xff, 0xf7, 0xf2, 0xf8, 0xff, 0xf3, 0xf2, 0xd8, 0xb4, 0xb0, 0xfb, 0xda, 0x99, 0x7c, 0x87, 0xe8,
	0x4f, 0x56, 0x5b, 0xe3, 0x4c, 0xdc, 0xdb, 0x21, 0x9e, 0xc6, 0x5d, 0x09, 0x4b, 0x61, 0xa1, 0x2d,
	0xa4, 0xaf, 0x2c, 0xba, 0xd5, 0xc4, 0x41, 0xde, 0x80, 0xd8, 0xc6, 0x53, 0xd6, 0x97, 0xe5, 0x0b,
	0xec, 0x93, 0x60, 0x1e, 0x2c, 0x26, 0xbc, 0x15, 0xf1, 0x19, 0x1b, 0xa1, 0xda, 0x68, 0xe1, 0x1a,
	0x0b, 0xc9, 0x11, 0x55, 0x0e, 0xc0, 0xf7, 0x68, 0xa3, 0x0b, 0x48, 0x7a, 0x6d, 0x0f, 0x89, 0xf8,
	0x84, 0x0d, 0x0a, 0x55, 0x97, 0x60, 0x93, 0x90, 0x70, 0xa7, 0xd2, 0x8f, 0x80, 0x85, 0x64, 0x35,
	0x63, 0x0c, 0x01, 0x51, 0x19, 0xfd, 0xac, 0x64, 0xe7, 0x37, 0xea, 0xc8, 0x9d, 0x8c, 0xcf, 0x59,
	0x9f, 0x92, 0x92, 0xdf, 0x78, 0x79, 0x9c, 0xb5, 0xb9, 0x1f, 0xac, 0xda, 0x09, 0x07, 0x8f, 0x5e,
	0xf0, 0xf6, 0x86, 0x8f, 0xe7, 0x4a, 0x0b, 0x58, 0x9a, 0xad, 0xa4, 0x10, 0x11, 0x3f, 0x80, 0x78,
	0xce, 0xc6, 0x85, 0xa9, 0x2a, 0xe5, 0x2a, 0xd0, 0x0e, 0x93, 0x70, 0xde, 0x5b, 0x4c, 0xf8, 0x57,
	0x94, 0x36, 0x6c, 0xc8, 0x01, 0x6b, 0xa3, 0x11, 0xfe, 0x4a, 0x35, 0x65, 0x7d, 0xa5, 0x25, 0xbc,
	0x51, 0xaa, 0x88, 0xb7, 0xc2, 0xbf, 0x15, 0x9d, 0x70, 0x0d, 0x92, 0xfb, 0x90, 0x77, 0xea, 0xfb,
	0xdc, 0xc2, 0x1f, 0x73, 0x4b, 0xdf, 0x03, 0x16, 0xdd, 0x37, 0xe8, 0xd4, 0x5a, 0x15, 0xc2, 0x29,
	0xa3, 0xff, 0x67, 0x3e, 0x63, 0xa1, 0x04, 0xb1, 0x25, 0xeb, 0xf1, 0x72, 0x94, 0xf9, 0x6f, 0xf7,
	0x03, 0xe6, 0x84, 0x7f, 0xcf, 0x70, 0x7d, 0xf9, 0x74, 0xb1, 0x51, 0xae, 0x6c, 0x56, 0x59, 0x61,
	0xaa, 0x5c, 0x82, 0x54, 0x98, 0x4b, 0x2b, 0xb4, 0xcc, 0x69, 0x41, 0x56, 0xcd, 0x3a, 0x3f, 0x6c,
	0xd4, 0x6a, 0x40, 0xf0, 0xea, 0x33, 0x00, 0x00, 0xff, 0xff, 0xef, 0x04, 0xc5, 0xf8, 0x66, 0x02,
	0x00, 0x00,
}
