version: "3"

services:
  drand_docker_demo_drand:
    container_name: drand_docker_demo_drand
    image: drandorg/go-drand:v2.0.0
    command: start --verbose --private-listen 0.0.0.0:8080 --control 8888 --public-listen 0.0.0.0:9080
    volumes:
      - drand_docker_demo_drand:/data/drand
    restart: always
    ports:
      - 8080:8080
      - 8888:8888
      - 9080:9080
  drand_docker_demo-nginx:
    container_name: drand_docker_demo-nginx
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 22180:80
      - 22181:81
      - 22443:443
    links:
      - drand_docker_demo_drand

volumes:
  drand_docker_demo_drand:
    external: true
    name: drand_docker_demo_drand
