FROM alpine

RUN apk update 
RUN apk add bash \
            git \
            make \
            clang \
            llvm \
            gmp \
            gmp-dev \
            libgmpxx  \
            libstdc++ \
            g++ \
            openssl \
            openssl-dev \ 
            go

RUN git clone https://github.com/dfinity/bn /bn
WORKDIR /bn
RUN make install
RUN make 
WORKDIR /
RUN rm -rf /bn

RUN mkdir -p /go/src
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
RUN go get github.com/dedis/drand
