// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto/share.proto

package crypto // import "github.com/dedis/drand/protobuf/crypto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// PrivateShare holds a share that is private for the given participant at the
// given index.
type PrivateShare struct {
	// index of the participant
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// the share itself
	Share                []byte   `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateShare) Reset()         { *m = PrivateShare{} }
func (m *PrivateShare) String() string { return proto.CompactTextString(m) }
func (*PrivateShare) ProtoMessage()    {}
func (*PrivateShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_3ef45179cf094846, []int{0}
}
func (m *PrivateShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateShare.Unmarshal(m, b)
}
func (m *PrivateShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateShare.Marshal(b, m, deterministic)
}
func (dst *PrivateShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateShare.Merge(dst, src)
}
func (m *PrivateShare) XXX_Size() int {
	return xxx_messageInfo_PrivateShare.Size(m)
}
func (m *PrivateShare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateShare.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateShare proto.InternalMessageInfo

func (m *PrivateShare) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PrivateShare) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

func init() {
	proto.RegisterType((*PrivateShare)(nil), "share.PrivateShare")
}

func init() { proto.RegisterFile("crypto/share.proto", fileDescriptor_share_3ef45179cf094846) }

var fileDescriptor_share_3ef45179cf094846 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x73, 0x94, 0xac, 0xb8, 0x78, 0x02, 0x8a, 0x32, 0xcb, 0x12, 0x4b, 0x52, 0x83, 0x41, 0x7c,
	0x21, 0x11, 0x2e, 0xd6, 0xcc, 0xbc, 0x94, 0xd4, 0x0a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde, 0x20,
	0x08, 0x07, 0x24, 0x0a, 0x56, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe1, 0x38, 0x69,
	0x44, 0xa9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0xa4, 0xa6,
	0x64, 0x16, 0xeb, 0xa7, 0x14, 0x25, 0xe6, 0xa5, 0xe8, 0x83, 0xad, 0x48, 0x2a, 0x4d, 0xd3, 0x87,
	0x58, 0x9c, 0xc4, 0x06, 0x16, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x63, 0x4b, 0xf5, 0xfb,
	0x89, 0x00, 0x00, 0x00,
}
