// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control/control.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	control/control.proto

It has these top-level messages:
	DKGRequest
	DKGResponse
	ReshareRequest
	GroupInfo
	ReshareResponse
	ShareRequest
	ShareResponse
	Ping
	Pong
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import element "github.com/dedis/drand/protobuf/crypto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DKGRequest struct {
	DkgGroup *GroupInfo `protobuf:"bytes,1,opt,name=dkg_group,json=dkgGroup" json:"dkg_group,omitempty"`
	IsLeader bool       `protobuf:"varint,2,opt,name=is_leader,json=isLeader" json:"is_leader,omitempty"`
}

func (m *DKGRequest) Reset()                    { *m = DKGRequest{} }
func (m *DKGRequest) String() string            { return proto.CompactTextString(m) }
func (*DKGRequest) ProtoMessage()               {}
func (*DKGRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DKGRequest) GetDkgGroup() *GroupInfo {
	if m != nil {
		return m.DkgGroup
	}
	return nil
}

func (m *DKGRequest) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

type DKGResponse struct {
}

func (m *DKGResponse) Reset()                    { *m = DKGResponse{} }
func (m *DKGResponse) String() string            { return proto.CompactTextString(m) }
func (*DKGResponse) ProtoMessage()               {}
func (*DKGResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ReshareRequest contains references to the old and new group to perform the
// resharing protocol.
type ReshareRequest struct {
	// Old group that needs to issue the shares for the new group
	// NOTE: It can be empty / nil. In that case, the drand node will try to
	// load the group he belongs to at the moment, if any, and use it as the old
	// group.
	Old      *GroupInfo `protobuf:"bytes,1,opt,name=old" json:"old,omitempty"`
	New      *GroupInfo `protobuf:"bytes,2,opt,name=new" json:"new,omitempty"`
	IsLeader bool       `protobuf:"varint,3,opt,name=is_leader,json=isLeader" json:"is_leader,omitempty"`
}

func (m *ReshareRequest) Reset()                    { *m = ReshareRequest{} }
func (m *ReshareRequest) String() string            { return proto.CompactTextString(m) }
func (*ReshareRequest) ProtoMessage()               {}
func (*ReshareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReshareRequest) GetOld() *GroupInfo {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *ReshareRequest) GetNew() *GroupInfo {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *ReshareRequest) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

type GroupInfo struct {
	// Types that are valid to be assigned to Location:
	//	*GroupInfo_Path
	//	*GroupInfo_Url
	Location isGroupInfo_Location `protobuf_oneof:"location"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isGroupInfo_Location interface {
	isGroupInfo_Location()
}

type GroupInfo_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,oneof"`
}
type GroupInfo_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,oneof"`
}

func (*GroupInfo_Path) isGroupInfo_Location() {}
func (*GroupInfo_Url) isGroupInfo_Location()  {}

func (m *GroupInfo) GetLocation() isGroupInfo_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GroupInfo) GetPath() string {
	if x, ok := m.GetLocation().(*GroupInfo_Path); ok {
		return x.Path
	}
	return ""
}

func (m *GroupInfo) GetUrl() string {
	if x, ok := m.GetLocation().(*GroupInfo_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GroupInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GroupInfo_OneofMarshaler, _GroupInfo_OneofUnmarshaler, _GroupInfo_OneofSizer, []interface{}{
		(*GroupInfo_Path)(nil),
		(*GroupInfo_Url)(nil),
	}
}

func _GroupInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GroupInfo)
	// location
	switch x := m.Location.(type) {
	case *GroupInfo_Path:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Path)
	case *GroupInfo_Url:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Url)
	case nil:
	default:
		return fmt.Errorf("GroupInfo.Location has unexpected type %T", x)
	}
	return nil
}

func _GroupInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GroupInfo)
	switch tag {
	case 1: // location.path
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &GroupInfo_Path{x}
		return true, err
	case 2: // location.url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &GroupInfo_Url{x}
		return true, err
	default:
		return false, nil
	}
}

func _GroupInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GroupInfo)
	// location
	switch x := m.Location.(type) {
	case *GroupInfo_Path:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Path)))
		n += len(x.Path)
	case *GroupInfo_Url:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Url)))
		n += len(x.Url)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReshareResponse struct {
}

func (m *ReshareResponse) Reset()                    { *m = ReshareResponse{} }
func (m *ReshareResponse) String() string            { return proto.CompactTextString(m) }
func (*ReshareResponse) ProtoMessage()               {}
func (*ReshareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Sharerequest requests the private share of a drand node
type ShareRequest struct {
}

func (m *ShareRequest) Reset()                    { *m = ShareRequest{} }
func (m *ShareRequest) String() string            { return proto.CompactTextString(m) }
func (*ShareRequest) ProtoMessage()               {}
func (*ShareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// ShareResponse holds the private share of a srand node
type ShareResponse struct {
	Index uint32          `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Share *element.Scalar `protobuf:"bytes,2,opt,name=share" json:"share,omitempty"`
}

func (m *ShareResponse) Reset()                    { *m = ShareResponse{} }
func (m *ShareResponse) String() string            { return proto.CompactTextString(m) }
func (*ShareResponse) ProtoMessage()               {}
func (*ShareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ShareResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ShareResponse) GetShare() *element.Scalar {
	if m != nil {
		return m.Share
	}
	return nil
}

type Ping struct {
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Pong struct {
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*DKGRequest)(nil), "control.DKGRequest")
	proto.RegisterType((*DKGResponse)(nil), "control.DKGResponse")
	proto.RegisterType((*ReshareRequest)(nil), "control.ReshareRequest")
	proto.RegisterType((*GroupInfo)(nil), "control.GroupInfo")
	proto.RegisterType((*ReshareResponse)(nil), "control.ReshareResponse")
	proto.RegisterType((*ShareRequest)(nil), "control.ShareRequest")
	proto.RegisterType((*ShareResponse)(nil), "control.ShareResponse")
	proto.RegisterType((*Ping)(nil), "control.Ping")
	proto.RegisterType((*Pong)(nil), "control.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Control service

type ControlClient interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	// Share returns the current share used by the node
	GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DKGResponse, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ReshareResponse, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/control.Control/PingPong", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	out := new(ShareResponse)
	err := grpc.Invoke(ctx, "/control.Control/GetShare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DKGResponse, error) {
	out := new(DKGResponse)
	err := grpc.Invoke(ctx, "/control.Control/InitDKG", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitReshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ReshareResponse, error) {
	out := new(ReshareResponse)
	err := grpc.Invoke(ctx, "/control.Control/InitReshare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Control service

type ControlServer interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(context.Context, *Ping) (*Pong, error)
	// Share returns the current share used by the node
	GetShare(context.Context, *ShareRequest) (*ShareResponse, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(context.Context, *DKGRequest) (*DKGResponse, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(context.Context, *ReshareRequest) (*ReshareResponse, error)
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.Control/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.Control/GetShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.Control/InitDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitDKG(ctx, req.(*DKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitReshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReshareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitReshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.Control/InitReshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitReshare(ctx, req.(*ReshareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "control.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _Control_PingPong_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _Control_GetShare_Handler,
		},
		{
			MethodName: "InitDKG",
			Handler:    _Control_InitDKG_Handler,
		},
		{
			MethodName: "InitReshare",
			Handler:    _Control_InitReshare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control/control.proto",
}

func init() { proto.RegisterFile("control/control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0xe8, 0xb6, 0x26, 0xaf, 0x64, 0x13, 0x8f, 0x0c, 0xaa, 0x70, 0x99, 0x22, 0x10, 0x83,
	0x43, 0x22, 0x0d, 0x89, 0x0b, 0x27, 0xca, 0xa4, 0x30, 0x6d, 0x07, 0x94, 0xde, 0x76, 0x99, 0xd2,
	0xd8, 0x4b, 0xad, 0xa6, 0x76, 0x70, 0x1c, 0x95, 0x7e, 0x69, 0x3e, 0x03, 0xb2, 0xf3, 0x87, 0xb4,
	0x88, 0x9d, 0xac, 0xdf, 0x1f, 0xbf, 0xf7, 0x7e, 0xf6, 0x83, 0xf3, 0x4c, 0x70, 0x25, 0x45, 0x11,
	0xb5, 0x67, 0x58, 0x4a, 0xa1, 0x04, 0x4e, 0x5a, 0xe8, 0x7b, 0x99, 0xdc, 0x95, 0x4a, 0x44, 0xb4,
	0xa0, 0x1b, 0xca, 0x55, 0x23, 0x07, 0xf7, 0x00, 0xd7, 0xb7, 0x71, 0x42, 0x7f, 0xd6, 0xb4, 0x52,
	0x18, 0x81, 0x43, 0xd6, 0xf9, 0x43, 0x2e, 0x45, 0x5d, 0xce, 0xac, 0x0b, 0xeb, 0x72, 0x7a, 0x85,
	0x61, 0x57, 0x2f, 0xd6, 0xec, 0x0d, 0x7f, 0x14, 0x89, 0x4d, 0xd6, 0xb9, 0x41, 0xf8, 0x06, 0x1c,
	0x56, 0x3d, 0x14, 0x34, 0x25, 0x54, 0xce, 0x9e, 0x5d, 0x58, 0x97, 0x76, 0x62, 0xb3, 0xea, 0xce,
	0xe0, 0xc0, 0x85, 0xa9, 0xa9, 0x5d, 0x95, 0x82, 0x57, 0x34, 0xd8, 0xc1, 0x69, 0x42, 0xab, 0x55,
	0x2a, 0x69, 0xd7, 0xee, 0x2d, 0x8c, 0x45, 0x41, 0x9e, 0x68, 0xa4, 0x65, 0xed, 0xe2, 0x74, 0x6b,
	0xaa, 0xff, 0xc7, 0xc5, 0xe9, 0x76, 0x7f, 0x92, 0xf1, 0xc1, 0x24, 0x5f, 0xc1, 0xe9, 0xed, 0xe8,
	0xc1, 0x51, 0x99, 0xaa, 0x95, 0x69, 0xeb, 0x7c, 0x1f, 0x25, 0x06, 0x21, 0xc2, 0xb8, 0x96, 0x85,
	0xe9, 0xa2, 0x49, 0x0d, 0xe6, 0x00, 0x76, 0x21, 0xb2, 0x54, 0x31, 0xc1, 0x83, 0x17, 0x70, 0xd6,
	0x4f, 0xdf, 0x06, 0x3a, 0x85, 0xe7, 0x8b, 0x41, 0x9c, 0xe0, 0x0e, 0xdc, 0xc5, 0xd0, 0x80, 0x1e,
	0x1c, 0x33, 0x4e, 0xe8, 0x2f, 0xd3, 0xca, 0x4d, 0x1a, 0x80, 0xef, 0xe0, 0xd8, 0xd4, 0x69, 0x13,
	0x9d, 0x85, 0xdd, 0x8f, 0x2c, 0xb2, 0xb4, 0x48, 0x65, 0xd2, 0xa8, 0xc1, 0x09, 0x1c, 0xfd, 0x60,
	0x3c, 0x37, 0xa7, 0xe0, 0xf9, 0xd5, 0x6f, 0x0b, 0x26, 0xdf, 0x9a, 0xec, 0xf8, 0x11, 0x6c, 0xad,
	0x69, 0x1e, 0xdd, 0xfe, 0x45, 0x34, 0xe5, 0x0f, 0xa0, 0xe0, 0x79, 0x30, 0xc2, 0x2f, 0x60, 0xc7,
	0x54, 0x99, 0xc1, 0xf0, 0xbc, 0x17, 0x87, 0x83, 0xfb, 0xaf, 0x0e, 0xe9, 0x36, 0xe0, 0x08, 0x3f,
	0xc3, 0xe4, 0x86, 0x33, 0x75, 0x7d, 0x1b, 0xe3, 0xcb, 0xde, 0xf4, 0x77, 0x61, 0x7c, 0x6f, 0x9f,
	0xec, 0xef, 0xcd, 0x61, 0xaa, 0xef, 0xb5, 0x2f, 0x86, 0xaf, 0x7b, 0xdb, 0xfe, 0x06, 0xf8, 0xb3,
	0x7f, 0x85, 0xae, 0xc6, 0xfc, 0xc3, 0xfd, 0xfb, 0x9c, 0xa9, 0x55, 0xbd, 0x0c, 0x33, 0xb1, 0x89,
	0x08, 0x25, 0xac, 0x8a, 0x88, 0x4c, 0x39, 0x89, 0xcc, 0xea, 0x2e, 0xeb, 0xc7, 0x6e, 0xd5, 0x97,
	0x27, 0x86, 0xf9, 0xf4, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x77, 0x62, 0xaa, 0x04, 0x03, 0x00,
	0x00,
}
