// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drand/api.proto

package drand

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PublicRandRequest requests a public random value that has been generated in a
// unbiasable way and verifiable.
type PublicRandRequest struct {
	// round uniquely identifies a beacon. If round == 0 (or unspecified), then
	// the response will contain the last.
	Round                uint64   `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicRandRequest) Reset()         { *m = PublicRandRequest{} }
func (m *PublicRandRequest) String() string { return proto.CompactTextString(m) }
func (*PublicRandRequest) ProtoMessage()    {}
func (*PublicRandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{0}
}

func (m *PublicRandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicRandRequest.Unmarshal(m, b)
}
func (m *PublicRandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicRandRequest.Marshal(b, m, deterministic)
}
func (m *PublicRandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicRandRequest.Merge(m, src)
}
func (m *PublicRandRequest) XXX_Size() int {
	return xxx_messageInfo_PublicRandRequest.Size(m)
}
func (m *PublicRandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicRandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicRandRequest proto.InternalMessageInfo

func (m *PublicRandRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// PublicRandResponse holds a signature which is the random value. It can be
// verified thanks to the distributed public key of the nodes that have ran the
// DKG protocol and is unbiasable. The randomness can be verified using the BLS
// verification routine with the message "round || previous_rand".
type PublicRandResponse struct {
	Round                uint64   `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Previous             []byte   `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Randomness           []byte   `protobuf:"bytes,4,opt,name=randomness,proto3" json:"randomness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicRandResponse) Reset()         { *m = PublicRandResponse{} }
func (m *PublicRandResponse) String() string { return proto.CompactTextString(m) }
func (*PublicRandResponse) ProtoMessage()    {}
func (*PublicRandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{1}
}

func (m *PublicRandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicRandResponse.Unmarshal(m, b)
}
func (m *PublicRandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicRandResponse.Marshal(b, m, deterministic)
}
func (m *PublicRandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicRandResponse.Merge(m, src)
}
func (m *PublicRandResponse) XXX_Size() int {
	return xxx_messageInfo_PublicRandResponse.Size(m)
}
func (m *PublicRandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicRandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicRandResponse proto.InternalMessageInfo

func (m *PublicRandResponse) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *PublicRandResponse) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *PublicRandResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PublicRandResponse) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

// PrivateRandRequest is the message to send when requesting a private random
// value.
type PrivateRandRequest struct {
	// Request must contains a public key towards which to encrypt the private
	// randomness.
	Request              *ECIES   `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateRandRequest) Reset()         { *m = PrivateRandRequest{} }
func (m *PrivateRandRequest) String() string { return proto.CompactTextString(m) }
func (*PrivateRandRequest) ProtoMessage()    {}
func (*PrivateRandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{2}
}

func (m *PrivateRandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateRandRequest.Unmarshal(m, b)
}
func (m *PrivateRandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateRandRequest.Marshal(b, m, deterministic)
}
func (m *PrivateRandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateRandRequest.Merge(m, src)
}
func (m *PrivateRandRequest) XXX_Size() int {
	return xxx_messageInfo_PrivateRandRequest.Size(m)
}
func (m *PrivateRandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateRandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateRandRequest proto.InternalMessageInfo

func (m *PrivateRandRequest) GetRequest() *ECIES {
	if m != nil {
		return m.Request
	}
	return nil
}

type PrivateRandResponse struct {
	// Response contains the private randomness encrypted towards the client's
	// request key.
	Response             *ECIES   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateRandResponse) Reset()         { *m = PrivateRandResponse{} }
func (m *PrivateRandResponse) String() string { return proto.CompactTextString(m) }
func (*PrivateRandResponse) ProtoMessage()    {}
func (*PrivateRandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{3}
}

func (m *PrivateRandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateRandResponse.Unmarshal(m, b)
}
func (m *PrivateRandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateRandResponse.Marshal(b, m, deterministic)
}
func (m *PrivateRandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateRandResponse.Merge(m, src)
}
func (m *PrivateRandResponse) XXX_Size() int {
	return xxx_messageInfo_PrivateRandResponse.Size(m)
}
func (m *PrivateRandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateRandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateRandResponse proto.InternalMessageInfo

func (m *PrivateRandResponse) GetResponse() *ECIES {
	if m != nil {
		return m.Response
	}
	return nil
}

type ECIES struct {
	Ephemeral            []byte   `protobuf:"bytes,1,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECIES) Reset()         { *m = ECIES{} }
func (m *ECIES) String() string { return proto.CompactTextString(m) }
func (*ECIES) ProtoMessage()    {}
func (*ECIES) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{4}
}

func (m *ECIES) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECIES.Unmarshal(m, b)
}
func (m *ECIES) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECIES.Marshal(b, m, deterministic)
}
func (m *ECIES) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECIES.Merge(m, src)
}
func (m *ECIES) XXX_Size() int {
	return xxx_messageInfo_ECIES.Size(m)
}
func (m *ECIES) XXX_DiscardUnknown() {
	xxx_messageInfo_ECIES.DiscardUnknown(m)
}

var xxx_messageInfo_ECIES proto.InternalMessageInfo

func (m *ECIES) GetEphemeral() []byte {
	if m != nil {
		return m.Ephemeral
	}
	return nil
}

func (m *ECIES) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *ECIES) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

// DistKeyRequest requests the distributed public key used during the randomness generation process
type DistKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistKeyRequest) Reset()         { *m = DistKeyRequest{} }
func (m *DistKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DistKeyRequest) ProtoMessage()    {}
func (*DistKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{5}
}

func (m *DistKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistKeyRequest.Unmarshal(m, b)
}
func (m *DistKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistKeyRequest.Marshal(b, m, deterministic)
}
func (m *DistKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistKeyRequest.Merge(m, src)
}
func (m *DistKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DistKeyRequest.Size(m)
}
func (m *DistKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistKeyRequest proto.InternalMessageInfo

type DistKeyResponse struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistKeyResponse) Reset()         { *m = DistKeyResponse{} }
func (m *DistKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DistKeyResponse) ProtoMessage()    {}
func (*DistKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{6}
}

func (m *DistKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistKeyResponse.Unmarshal(m, b)
}
func (m *DistKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistKeyResponse.Marshal(b, m, deterministic)
}
func (m *DistKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistKeyResponse.Merge(m, src)
}
func (m *DistKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DistKeyResponse.Size(m)
}
func (m *DistKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistKeyResponse proto.InternalMessageInfo

func (m *DistKeyResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type HomeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeRequest) Reset()         { *m = HomeRequest{} }
func (m *HomeRequest) String() string { return proto.CompactTextString(m) }
func (*HomeRequest) ProtoMessage()    {}
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{7}
}

func (m *HomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeRequest.Unmarshal(m, b)
}
func (m *HomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeRequest.Marshal(b, m, deterministic)
}
func (m *HomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeRequest.Merge(m, src)
}
func (m *HomeRequest) XXX_Size() int {
	return xxx_messageInfo_HomeRequest.Size(m)
}
func (m *HomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeRequest proto.InternalMessageInfo

type HomeResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeResponse) Reset()         { *m = HomeResponse{} }
func (m *HomeResponse) String() string { return proto.CompactTextString(m) }
func (*HomeResponse) ProtoMessage()    {}
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{8}
}

func (m *HomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeResponse.Unmarshal(m, b)
}
func (m *HomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeResponse.Marshal(b, m, deterministic)
}
func (m *HomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeResponse.Merge(m, src)
}
func (m *HomeResponse) XXX_Size() int {
	return xxx_messageInfo_HomeResponse.Size(m)
}
func (m *HomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HomeResponse proto.InternalMessageInfo

func (m *HomeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupRequest) Reset()         { *m = GroupRequest{} }
func (m *GroupRequest) String() string { return proto.CompactTextString(m) }
func (*GroupRequest) ProtoMessage()    {}
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{9}
}

func (m *GroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRequest.Unmarshal(m, b)
}
func (m *GroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRequest.Marshal(b, m, deterministic)
}
func (m *GroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRequest.Merge(m, src)
}
func (m *GroupRequest) XXX_Size() int {
	return xxx_messageInfo_GroupRequest.Size(m)
}
func (m *GroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRequest proto.InternalMessageInfo

// GroupResponse contains the Group information currently used by the drand node
// in HEXADECIMAL the same format as the group.toml file.
type GroupResponse struct {
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// in ms
	Period               uint32   `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Distkey              []string `protobuf:"bytes,5,rep,name=distkey,proto3" json:"distkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupResponse) Reset()         { *m = GroupResponse{} }
func (m *GroupResponse) String() string { return proto.CompactTextString(m) }
func (*GroupResponse) ProtoMessage()    {}
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{10}
}

func (m *GroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupResponse.Unmarshal(m, b)
}
func (m *GroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupResponse.Marshal(b, m, deterministic)
}
func (m *GroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupResponse.Merge(m, src)
}
func (m *GroupResponse) XXX_Size() int {
	return xxx_messageInfo_GroupResponse.Size(m)
}
func (m *GroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupResponse proto.InternalMessageInfo

func (m *GroupResponse) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *GroupResponse) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *GroupResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GroupResponse) GetDistkey() []string {
	if m != nil {
		return m.Distkey
	}
	return nil
}

// Node represents the information about a drand's node
type Node struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	TLS                  bool     `protobuf:"varint,3,opt,name=TLS,proto3" json:"TLS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0cff3fc81cf7d79, []int{11}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Node) GetTLS() bool {
	if m != nil {
		return m.TLS
	}
	return false
}

func init() {
	proto.RegisterType((*PublicRandRequest)(nil), "drand.PublicRandRequest")
	proto.RegisterType((*PublicRandResponse)(nil), "drand.PublicRandResponse")
	proto.RegisterType((*PrivateRandRequest)(nil), "drand.PrivateRandRequest")
	proto.RegisterType((*PrivateRandResponse)(nil), "drand.PrivateRandResponse")
	proto.RegisterType((*ECIES)(nil), "drand.ECIES")
	proto.RegisterType((*DistKeyRequest)(nil), "drand.DistKeyRequest")
	proto.RegisterType((*DistKeyResponse)(nil), "drand.DistKeyResponse")
	proto.RegisterType((*HomeRequest)(nil), "drand.HomeRequest")
	proto.RegisterType((*HomeResponse)(nil), "drand.HomeResponse")
	proto.RegisterType((*GroupRequest)(nil), "drand.GroupRequest")
	proto.RegisterType((*GroupResponse)(nil), "drand.GroupResponse")
	proto.RegisterType((*Node)(nil), "drand.Node")
}

func init() { proto.RegisterFile("drand/api.proto", fileDescriptor_c0cff3fc81cf7d79) }

var fileDescriptor_c0cff3fc81cf7d79 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdb, 0x6e, 0x13, 0x31,
	0x10, 0x55, 0x9a, 0x4b, 0x9b, 0xc9, 0xa6, 0x97, 0x49, 0x5b, 0xd2, 0x55, 0x85, 0xca, 0x02, 0x25,
	0xf4, 0x21, 0x91, 0xca, 0x1b, 0x02, 0x21, 0x41, 0x2b, 0x40, 0x45, 0xa8, 0xda, 0xf2, 0x54, 0xc4,
	0xc3, 0x26, 0x76, 0x13, 0x8b, 0x64, 0xbd, 0xd8, 0xde, 0x8a, 0x0a, 0xf1, 0x52, 0xf1, 0x07, 0x7c,
	0x0c, 0x1f, 0xc2, 0x2f, 0xf0, 0x21, 0xc8, 0x63, 0x27, 0xd9, 0xb4, 0x7d, 0xf3, 0x39, 0x33, 0x73,
	0x3c, 0x67, 0x7d, 0x12, 0x58, 0x63, 0x2a, 0x49, 0x59, 0x2f, 0xc9, 0x44, 0x37, 0x53, 0xd2, 0x48,
	0xac, 0x12, 0x11, 0xee, 0x0e, 0xa5, 0x1c, 0x8e, 0xb9, 0x2d, 0xf4, 0x92, 0x34, 0x95, 0x26, 0x31,
	0x42, 0xa6, 0xda, 0x35, 0x45, 0x4f, 0x61, 0xe3, 0x34, 0xef, 0x8f, 0xc5, 0x20, 0x4e, 0x52, 0x16,
	0xf3, 0x6f, 0x39, 0xd7, 0x06, 0x37, 0xa1, 0xaa, 0x64, 0x9e, 0xb2, 0x76, 0x69, 0xaf, 0xd4, 0xa9,
	0xc4, 0x0e, 0x44, 0xbf, 0x4a, 0x80, 0xc5, 0x5e, 0x9d, 0xc9, 0x54, 0xf3, 0xbb, 0x9b, 0x31, 0x84,
	0x95, 0x4c, 0xf1, 0x4b, 0x21, 0x73, 0xdd, 0x5e, 0xda, 0x2b, 0x75, 0x82, 0x78, 0x86, 0x71, 0x17,
	0xea, 0x5a, 0x0c, 0xd3, 0xc4, 0xe4, 0x8a, 0xb7, 0xcb, 0x54, 0x9c, 0x13, 0x78, 0x1f, 0xc0, 0xee,
	0x2d, 0x27, 0x29, 0xd7, 0xba, 0x5d, 0xa1, 0x72, 0x81, 0x89, 0x5e, 0x00, 0x9e, 0x2a, 0x71, 0x99,
	0x18, 0x5e, 0x5c, 0x79, 0x1f, 0x96, 0x95, 0x3b, 0xd2, 0x75, 0x8d, 0xc3, 0xa0, 0x4b, 0xf6, 0xbb,
	0xc7, 0x6f, 0xde, 0x1f, 0x9f, 0xc5, 0xd3, 0x62, 0xf4, 0x0a, 0x5a, 0x0b, 0xd3, 0xde, 0x44, 0x07,
	0x56, 0x94, 0x3f, 0x93, 0x8f, 0x9b, 0xf3, 0xb3, 0x6a, 0xf4, 0x19, 0xaa, 0x44, 0x59, 0x17, 0x3c,
	0x1b, 0xf1, 0x09, 0x57, 0xc9, 0x98, 0x66, 0x82, 0x78, 0x4e, 0x58, 0x17, 0x03, 0x91, 0x8d, 0xb8,
	0x32, 0xfc, 0xbb, 0xf1, 0x5f, 0xa0, 0xc0, 0xd8, 0xaf, 0x96, 0xca, 0x74, 0x30, 0xf5, 0xef, 0x40,
	0xb4, 0x0e, 0xab, 0x47, 0x42, 0x9b, 0x13, 0x7e, 0xe5, 0x7d, 0x45, 0x0f, 0x61, 0x6d, 0xc6, 0xf8,
	0x5d, 0xd7, 0xa1, 0xfc, 0x95, 0x5f, 0x79, 0x4d, 0x7b, 0x8c, 0x9a, 0xd0, 0x78, 0x27, 0x27, 0x7c,
	0x3a, 0xb3, 0x0f, 0x81, 0x83, 0x7e, 0x60, 0x1b, 0x6a, 0xda, 0x24, 0x26, 0xd7, 0xb4, 0x66, 0x3d,
	0xf6, 0x28, 0x5a, 0x85, 0xe0, 0xad, 0x92, 0x79, 0x36, 0x9d, 0xbb, 0x2e, 0x41, 0xd3, 0x13, 0x7e,
	0x72, 0x17, 0xea, 0x66, 0xa4, 0xb8, 0x1e, 0xc9, 0x31, 0xa3, 0x0b, 0x9b, 0xf1, 0x9c, 0xb0, 0xba,
	0x19, 0x57, 0x42, 0x32, 0x32, 0xd1, 0x8c, 0x3d, 0xc2, 0x07, 0xd6, 0x1b, 0xe3, 0xf6, 0xf1, 0xca,
	0x9d, 0xc6, 0x61, 0xc3, 0x7f, 0xc9, 0x8f, 0x92, 0xf1, 0xd8, 0x55, 0xb0, 0x0d, 0xcb, 0x4c, 0x68,
	0x63, 0x7d, 0x54, 0xf7, 0xca, 0x9d, 0x7a, 0x3c, 0x85, 0xd1, 0x11, 0x54, 0x6c, 0xa3, 0xed, 0x48,
	0x18, 0x53, 0x36, 0x03, 0x6e, 0xeb, 0x29, 0x2c, 0xfa, 0xaf, 0x93, 0x7f, 0xcb, 0x7c, 0xfa, 0x70,
	0x46, 0x5b, 0xac, 0xc4, 0xf6, 0x78, 0xf8, 0xa7, 0x0c, 0x35, 0x97, 0x55, 0x9c, 0x00, 0xcc, 0x53,
	0x8b, 0x6d, 0xbf, 0xcc, 0xad, 0xd0, 0x87, 0x3b, 0x77, 0x54, 0xfc, 0x9b, 0x1f, 0x5c, 0xff, 0xfd,
	0xf7, 0x7b, 0xe9, 0x11, 0x36, 0xe8, 0x47, 0x94, 0x51, 0xc3, 0xf9, 0x16, 0xb6, 0x0a, 0xb0, 0xf7,
	0x83, 0x72, 0xff, 0x13, 0xbf, 0x40, 0xa3, 0x10, 0x30, 0x9c, 0xa9, 0xde, 0x8a, 0x6c, 0x18, 0xde,
	0x55, 0xf2, 0x37, 0xde, 0xa3, 0x1b, 0x37, 0xa2, 0xc0, 0x5d, 0xe1, 0x3a, 0x9e, 0x97, 0x0e, 0xf0,
	0x04, 0xaa, 0xf4, 0x44, 0xd8, 0xf2, 0xd3, 0xc5, 0x17, 0x0c, 0x37, 0x17, 0xc9, 0x45, 0x31, 0x5c,
	0x23, 0x31, 0x91, 0x5e, 0xc8, 0xde, 0x90, 0x34, 0xce, 0x60, 0xd9, 0x87, 0x0b, 0xb7, 0xfc, 0xe4,
	0x62, 0xfc, 0xc2, 0xed, 0x9b, 0xb4, 0x97, 0xdc, 0x21, 0xc9, 0x16, 0x6e, 0xcc, 0x25, 0xfd, 0x03,
	0xe2, 0x4b, 0xa8, 0xd8, 0xf4, 0x21, 0xfa, 0xd1, 0x42, 0x32, 0xc3, 0xd6, 0x02, 0xe7, 0xb5, 0x02,
	0xd2, 0xaa, 0x61, 0xc5, 0x6a, 0xbd, 0x7e, 0x72, 0xfe, 0x78, 0x28, 0xcc, 0x28, 0xef, 0x77, 0x07,
	0x72, 0xd2, 0x63, 0x9c, 0x09, 0xdd, 0x73, 0xff, 0x6c, 0xf4, 0x87, 0xd5, 0xcf, 0x2f, 0x1c, 0xec,
	0xd7, 0x08, 0x3f, 0xfb, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x3b, 0x0f, 0x1a, 0xf8, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublicClient is the client API for Public service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicClient interface {
	// PublicRand is the method that returns the publicly verifiable randomness
	// generated by the drand network.
	PublicRand(ctx context.Context, in *PublicRandRequest, opts ...grpc.CallOption) (*PublicRandResponse, error)
	// PrivateRand is the method that returns the private randomness generated
	// by the drand node only.
	PrivateRand(ctx context.Context, in *PrivateRandRequest, opts ...grpc.CallOption) (*PrivateRandResponse, error)
	// Group is the method that returns the group descrition that the drand
	// endpoint belongs to
	Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	// DistKey returns the distributed key from which drand node endpoint get a share
	DistKey(ctx context.Context, in *DistKeyRequest, opts ...grpc.CallOption) (*DistKeyResponse, error)
	// Home is a simple endpoint
	Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error)
}

type publicClient struct {
	cc *grpc.ClientConn
}

func NewPublicClient(cc *grpc.ClientConn) PublicClient {
	return &publicClient{cc}
}

func (c *publicClient) PublicRand(ctx context.Context, in *PublicRandRequest, opts ...grpc.CallOption) (*PublicRandResponse, error) {
	out := new(PublicRandResponse)
	err := c.cc.Invoke(ctx, "/drand.Public/PublicRand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) PrivateRand(ctx context.Context, in *PrivateRandRequest, opts ...grpc.CallOption) (*PrivateRandResponse, error) {
	out := new(PrivateRandResponse)
	err := c.cc.Invoke(ctx, "/drand.Public/PrivateRand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, "/drand.Public/Group", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) DistKey(ctx context.Context, in *DistKeyRequest, opts ...grpc.CallOption) (*DistKeyResponse, error) {
	out := new(DistKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Public/DistKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicClient) Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error) {
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, "/drand.Public/Home", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServer is the server API for Public service.
type PublicServer interface {
	// PublicRand is the method that returns the publicly verifiable randomness
	// generated by the drand network.
	PublicRand(context.Context, *PublicRandRequest) (*PublicRandResponse, error)
	// PrivateRand is the method that returns the private randomness generated
	// by the drand node only.
	PrivateRand(context.Context, *PrivateRandRequest) (*PrivateRandResponse, error)
	// Group is the method that returns the group descrition that the drand
	// endpoint belongs to
	Group(context.Context, *GroupRequest) (*GroupResponse, error)
	// DistKey returns the distributed key from which drand node endpoint get a share
	DistKey(context.Context, *DistKeyRequest) (*DistKeyResponse, error)
	// Home is a simple endpoint
	Home(context.Context, *HomeRequest) (*HomeResponse, error)
}

// UnimplementedPublicServer can be embedded to have forward compatible implementations.
type UnimplementedPublicServer struct {
}

func (*UnimplementedPublicServer) PublicRand(ctx context.Context, req *PublicRandRequest) (*PublicRandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicRand not implemented")
}
func (*UnimplementedPublicServer) PrivateRand(ctx context.Context, req *PrivateRandRequest) (*PrivateRandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateRand not implemented")
}
func (*UnimplementedPublicServer) Group(ctx context.Context, req *GroupRequest) (*GroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Group not implemented")
}
func (*UnimplementedPublicServer) DistKey(ctx context.Context, req *DistKeyRequest) (*DistKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistKey not implemented")
}
func (*UnimplementedPublicServer) Home(ctx context.Context, req *HomeRequest) (*HomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Home not implemented")
}

func RegisterPublicServer(s *grpc.Server, srv PublicServer) {
	s.RegisterService(&_Public_serviceDesc, srv)
}

func _Public_PublicRand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicRandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).PublicRand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Public/PublicRand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).PublicRand(ctx, req.(*PublicRandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_PrivateRand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateRandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).PrivateRand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Public/PrivateRand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).PrivateRand(ctx, req.(*PrivateRandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_Group_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).Group(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Public/Group",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).Group(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_DistKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).DistKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Public/DistKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).DistKey(ctx, req.(*DistKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Public_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Public/Home",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServer).Home(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Public_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drand.Public",
	HandlerType: (*PublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicRand",
			Handler:    _Public_PublicRand_Handler,
		},
		{
			MethodName: "PrivateRand",
			Handler:    _Public_PrivateRand_Handler,
		},
		{
			MethodName: "Group",
			Handler:    _Public_Group_Handler,
		},
		{
			MethodName: "DistKey",
			Handler:    _Public_DistKey_Handler,
		},
		{
			MethodName: "Home",
			Handler:    _Public_Home_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drand/api.proto",
}
