// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drand/client.proto

package drand // import "github.com/dedis/drand/protobuf/drand"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import crypto "github.com/dedis/drand/protobuf/crypto"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PublicRandRequest requests a public random value that has been generated in a
// unbiasable way and verifiable.
type PublicRandRequest struct {
	// round uniquely identifies a beacon. If round == 0, then the response will
	// contain the last.
	// XXX better ways to do that...
	Round                uint64   `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicRandRequest) Reset()         { *m = PublicRandRequest{} }
func (m *PublicRandRequest) String() string { return proto.CompactTextString(m) }
func (*PublicRandRequest) ProtoMessage()    {}
func (*PublicRandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{0}
}
func (m *PublicRandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicRandRequest.Unmarshal(m, b)
}
func (m *PublicRandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicRandRequest.Marshal(b, m, deterministic)
}
func (dst *PublicRandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicRandRequest.Merge(dst, src)
}
func (m *PublicRandRequest) XXX_Size() int {
	return xxx_messageInfo_PublicRandRequest.Size(m)
}
func (m *PublicRandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicRandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicRandRequest proto.InternalMessageInfo

func (m *PublicRandRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// PublicRandResponse holds a signature which is the random value. It can be
// verified thanks to the distributed public key of the nodes that have ran the
// DKG protocol and is unbiasable. The randomness can be verified using the BLS
// verification routine with the message "round || previous_rand".
type PublicRandResponse struct {
	Round                uint64   `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Previous             []byte   `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Randomness           []byte   `protobuf:"bytes,3,opt,name=randomness,proto3" json:"randomness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicRandResponse) Reset()         { *m = PublicRandResponse{} }
func (m *PublicRandResponse) String() string { return proto.CompactTextString(m) }
func (*PublicRandResponse) ProtoMessage()    {}
func (*PublicRandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{1}
}
func (m *PublicRandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicRandResponse.Unmarshal(m, b)
}
func (m *PublicRandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicRandResponse.Marshal(b, m, deterministic)
}
func (dst *PublicRandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicRandResponse.Merge(dst, src)
}
func (m *PublicRandResponse) XXX_Size() int {
	return xxx_messageInfo_PublicRandResponse.Size(m)
}
func (m *PublicRandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicRandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicRandResponse proto.InternalMessageInfo

func (m *PublicRandResponse) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *PublicRandResponse) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *PublicRandResponse) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

// PrivateRandRequest is the message to send when requesting a private random
// value.
type PrivateRandRequest struct {
	// Request must contains a public key towards which to encrypt the private
	// randomness.
	Request              *ECIESObject `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrivateRandRequest) Reset()         { *m = PrivateRandRequest{} }
func (m *PrivateRandRequest) String() string { return proto.CompactTextString(m) }
func (*PrivateRandRequest) ProtoMessage()    {}
func (*PrivateRandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{2}
}
func (m *PrivateRandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateRandRequest.Unmarshal(m, b)
}
func (m *PrivateRandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateRandRequest.Marshal(b, m, deterministic)
}
func (dst *PrivateRandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateRandRequest.Merge(dst, src)
}
func (m *PrivateRandRequest) XXX_Size() int {
	return xxx_messageInfo_PrivateRandRequest.Size(m)
}
func (m *PrivateRandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateRandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateRandRequest proto.InternalMessageInfo

func (m *PrivateRandRequest) GetRequest() *ECIESObject {
	if m != nil {
		return m.Request
	}
	return nil
}

type PrivateRandResponse struct {
	// Response contains the private randomness encrypted towards the client's
	// request key.
	Response             *ECIESObject `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrivateRandResponse) Reset()         { *m = PrivateRandResponse{} }
func (m *PrivateRandResponse) String() string { return proto.CompactTextString(m) }
func (*PrivateRandResponse) ProtoMessage()    {}
func (*PrivateRandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{3}
}
func (m *PrivateRandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateRandResponse.Unmarshal(m, b)
}
func (m *PrivateRandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateRandResponse.Marshal(b, m, deterministic)
}
func (dst *PrivateRandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateRandResponse.Merge(dst, src)
}
func (m *PrivateRandResponse) XXX_Size() int {
	return xxx_messageInfo_PrivateRandResponse.Size(m)
}
func (m *PrivateRandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateRandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateRandResponse proto.InternalMessageInfo

func (m *PrivateRandResponse) GetResponse() *ECIESObject {
	if m != nil {
		return m.Response
	}
	return nil
}

type ECIESObject struct {
	Ephemeral            *crypto.Point `protobuf:"bytes,1,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Ciphertext           []byte        `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce                []byte        `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ECIESObject) Reset()         { *m = ECIESObject{} }
func (m *ECIESObject) String() string { return proto.CompactTextString(m) }
func (*ECIESObject) ProtoMessage()    {}
func (*ECIESObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{4}
}
func (m *ECIESObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECIESObject.Unmarshal(m, b)
}
func (m *ECIESObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECIESObject.Marshal(b, m, deterministic)
}
func (dst *ECIESObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECIESObject.Merge(dst, src)
}
func (m *ECIESObject) XXX_Size() int {
	return xxx_messageInfo_ECIESObject.Size(m)
}
func (m *ECIESObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ECIESObject.DiscardUnknown(m)
}

var xxx_messageInfo_ECIESObject proto.InternalMessageInfo

func (m *ECIESObject) GetEphemeral() *crypto.Point {
	if m != nil {
		return m.Ephemeral
	}
	return nil
}

func (m *ECIESObject) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *ECIESObject) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

// DistKeyRequest requests the distributed public key used during the randomness generation process
type DistKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistKeyRequest) Reset()         { *m = DistKeyRequest{} }
func (m *DistKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DistKeyRequest) ProtoMessage()    {}
func (*DistKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{5}
}
func (m *DistKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistKeyRequest.Unmarshal(m, b)
}
func (m *DistKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistKeyRequest.Marshal(b, m, deterministic)
}
func (dst *DistKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistKeyRequest.Merge(dst, src)
}
func (m *DistKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DistKeyRequest.Size(m)
}
func (m *DistKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistKeyRequest proto.InternalMessageInfo

type DistKeyResponse struct {
	Key                  *crypto.Point `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DistKeyResponse) Reset()         { *m = DistKeyResponse{} }
func (m *DistKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DistKeyResponse) ProtoMessage()    {}
func (*DistKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_8450c28a8ef3f5a5, []int{6}
}
func (m *DistKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistKeyResponse.Unmarshal(m, b)
}
func (m *DistKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistKeyResponse.Marshal(b, m, deterministic)
}
func (dst *DistKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistKeyResponse.Merge(dst, src)
}
func (m *DistKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DistKeyResponse.Size(m)
}
func (m *DistKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistKeyResponse proto.InternalMessageInfo

func (m *DistKeyResponse) GetKey() *crypto.Point {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicRandRequest)(nil), "drand.PublicRandRequest")
	proto.RegisterType((*PublicRandResponse)(nil), "drand.PublicRandResponse")
	proto.RegisterType((*PrivateRandRequest)(nil), "drand.PrivateRandRequest")
	proto.RegisterType((*PrivateRandResponse)(nil), "drand.PrivateRandResponse")
	proto.RegisterType((*ECIESObject)(nil), "drand.ECIESObject")
	proto.RegisterType((*DistKeyRequest)(nil), "drand.DistKeyRequest")
	proto.RegisterType((*DistKeyResponse)(nil), "drand.DistKeyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RandomnessClient is the client API for Randomness service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RandomnessClient interface {
	Public(ctx context.Context, in *PublicRandRequest, opts ...grpc.CallOption) (*PublicRandResponse, error)
	Private(ctx context.Context, in *PrivateRandRequest, opts ...grpc.CallOption) (*PrivateRandResponse, error)
}

type randomnessClient struct {
	cc *grpc.ClientConn
}

func NewRandomnessClient(cc *grpc.ClientConn) RandomnessClient {
	return &randomnessClient{cc}
}

func (c *randomnessClient) Public(ctx context.Context, in *PublicRandRequest, opts ...grpc.CallOption) (*PublicRandResponse, error) {
	out := new(PublicRandResponse)
	err := c.cc.Invoke(ctx, "/drand.Randomness/Public", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *randomnessClient) Private(ctx context.Context, in *PrivateRandRequest, opts ...grpc.CallOption) (*PrivateRandResponse, error) {
	out := new(PrivateRandResponse)
	err := c.cc.Invoke(ctx, "/drand.Randomness/Private", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomnessServer is the server API for Randomness service.
type RandomnessServer interface {
	Public(context.Context, *PublicRandRequest) (*PublicRandResponse, error)
	Private(context.Context, *PrivateRandRequest) (*PrivateRandResponse, error)
}

func RegisterRandomnessServer(s *grpc.Server, srv RandomnessServer) {
	s.RegisterService(&_Randomness_serviceDesc, srv)
}

func _Randomness_Public_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicRandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomnessServer).Public(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Randomness/Public",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomnessServer).Public(ctx, req.(*PublicRandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Randomness_Private_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateRandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomnessServer).Private(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Randomness/Private",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomnessServer).Private(ctx, req.(*PrivateRandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Randomness_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drand.Randomness",
	HandlerType: (*RandomnessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Public",
			Handler:    _Randomness_Public_Handler,
		},
		{
			MethodName: "Private",
			Handler:    _Randomness_Private_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drand/client.proto",
}

// InfoClient is the client API for Info service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfoClient interface {
	DistKey(ctx context.Context, in *DistKeyRequest, opts ...grpc.CallOption) (*DistKeyResponse, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) DistKey(ctx context.Context, in *DistKeyRequest, opts ...grpc.CallOption) (*DistKeyResponse, error) {
	out := new(DistKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Info/DistKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServer is the server API for Info service.
type InfoServer interface {
	DistKey(context.Context, *DistKeyRequest) (*DistKeyResponse, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_DistKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).DistKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Info/DistKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).DistKey(ctx, req.(*DistKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drand.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistKey",
			Handler:    _Info_DistKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drand/client.proto",
}

func init() { proto.RegisterFile("drand/client.proto", fileDescriptor_client_8450c28a8ef3f5a5) }

var fileDescriptor_client_8450c28a8ef3f5a5 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0x56, 0xfa, 0x97, 0x74, 0x02, 0x2d, 0x9d, 0x96, 0x2a, 0xac, 0x22, 0x14, 0xad, 0x84, 0x28,
	0xa8, 0x5a, 0x4b, 0xe9, 0x8d, 0x63, 0x21, 0x87, 0x8a, 0x03, 0xd1, 0x22, 0x38, 0xf4, 0x00, 0xda,
	0x9f, 0x49, 0x62, 0xba, 0xb1, 0x5d, 0xdb, 0x5b, 0x11, 0x21, 0x2e, 0xbc, 0x02, 0xef, 0xc4, 0x0b,
	0xf0, 0x0a, 0x3c, 0x08, 0x8a, 0xd7, 0xdd, 0x6e, 0x69, 0xe8, 0x6d, 0x66, 0xbe, 0xf1, 0x37, 0xf3,
	0x7d, 0x23, 0x03, 0xe6, 0x3a, 0x11, 0x39, 0xcb, 0x0a, 0x4e, 0xc2, 0x46, 0x4a, 0x4b, 0x2b, 0x71,
	0xd3, 0xd5, 0x82, 0x83, 0x4c, 0x2f, 0x94, 0x95, 0x8c, 0x0a, 0x9a, 0xd7, 0x60, 0xd0, 0x9f, 0x4a,
	0x39, 0x2d, 0x88, 0x25, 0x8a, 0xb3, 0x44, 0x08, 0x69, 0x13, 0xcb, 0xa5, 0x30, 0x15, 0x1a, 0xbe,
	0x80, 0xbd, 0x71, 0x99, 0x16, 0x3c, 0x8b, 0x13, 0x91, 0xc7, 0x74, 0x59, 0x92, 0xb1, 0x78, 0x00,
	0x9b, 0x5a, 0x96, 0x22, 0xef, 0xb5, 0x06, 0xad, 0xa3, 0x8d, 0xb8, 0x4a, 0xc2, 0x09, 0x60, 0xb3,
	0xd5, 0x28, 0x29, 0x0c, 0xad, 0xee, 0xc5, 0x00, 0x3a, 0x4a, 0xd3, 0x15, 0x97, 0xa5, 0xe9, 0xad,
	0x0d, 0x5a, 0x47, 0x0f, 0xe2, 0x3a, 0xc7, 0xa7, 0x00, 0xcb, 0x75, 0xe5, 0x5c, 0x90, 0x31, 0xbd,
	0x75, 0x87, 0x36, 0x2a, 0xe1, 0x29, 0xe0, 0x58, 0xf3, 0xab, 0xc4, 0x52, 0x73, 0xa7, 0x63, 0x68,
	0xeb, 0x2a, 0x74, 0x93, 0xba, 0x43, 0x8c, 0x9c, 0xea, 0x68, 0xf4, 0xfa, 0x6c, 0xf4, 0xfe, 0x5d,
	0xfa, 0x85, 0x32, 0x1b, 0x5f, 0xb7, 0x84, 0x23, 0xd8, 0xbf, 0xc5, 0xe1, 0x97, 0x8d, 0xa0, 0xa3,
	0x7d, 0x7c, 0x0f, 0x4b, 0xdd, 0x13, 0x5e, 0x42, 0xb7, 0x01, 0xe0, 0x31, 0x6c, 0x93, 0x9a, 0xd1,
	0x9c, 0x74, 0x52, 0xf8, 0xf7, 0x3b, 0xd1, 0xb5, 0xdb, 0x63, 0xc9, 0x85, 0x8d, 0x6f, 0x1a, 0x96,
	0x3a, 0x33, 0xae, 0x66, 0xa4, 0x2d, 0x7d, 0xb5, 0xde, 0x85, 0x46, 0x65, 0xe9, 0x9c, 0x90, 0x22,
	0x23, 0x6f, 0x41, 0x95, 0x84, 0x8f, 0x60, 0xe7, 0x0d, 0x37, 0xf6, 0x2d, 0x2d, 0xbc, 0xf2, 0xf0,
	0x04, 0x76, 0xeb, 0x8a, 0xd7, 0x31, 0x80, 0xf5, 0x0b, 0x5a, 0xfc, 0x67, 0x85, 0x25, 0x34, 0xfc,
	0xd5, 0x02, 0x88, 0x6b, 0x4f, 0x31, 0x81, 0xad, 0xea, 0x76, 0xd8, 0xf3, 0x82, 0xef, 0x5c, 0x3d,
	0x78, 0xb2, 0x02, 0xf1, 0x3e, 0x84, 0x3f, 0x7e, 0xff, 0xf9, 0xb9, 0xd6, 0xc7, 0x36, 0x53, 0x0e,
	0x3c, 0xdf, 0xc3, 0x5d, 0x1f, 0xb2, 0x6f, 0xee, 0xe2, 0xdf, 0xf1, 0x03, 0xb4, 0xbd, 0xe5, 0x58,
	0x33, 0xdd, 0x39, 0x63, 0x10, 0xac, 0x82, 0xfc, 0x94, 0x7d, 0x37, 0xe5, 0x61, 0xd8, 0x61, 0xaa,
	0x42, 0x5f, 0xb5, 0x5e, 0x0e, 0x3f, 0xc1, 0xc6, 0x99, 0x98, 0x48, 0xfc, 0x08, 0x6d, 0xef, 0x02,
	0x3e, 0xf6, 0x1c, 0xb7, 0x7d, 0x0a, 0x0e, 0xff, 0x2d, 0x7b, 0xda, 0xbe, 0xa3, 0x3d, 0xbc, 0x59,
	0xbe, 0x8b, 0xdb, 0x2c, 0xe7, 0xc6, 0x7e, 0xbe, 0xa0, 0xc5, 0xe9, 0xf3, 0xf3, 0x67, 0x53, 0x6e,
	0x67, 0x65, 0x1a, 0x65, 0x72, 0xce, 0x72, 0xca, 0xb9, 0x61, 0xd5, 0x17, 0x73, 0x1f, 0x24, 0x2d,
	0x27, 0x55, 0x9a, 0x6e, 0xb9, 0xfc, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x12, 0x37,
	0xe2, 0x81, 0x03, 0x00, 0x00,
}
