// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drand/control.proto

package drand // import "github.com/drand/drand/protobuf/drand"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitDKGPacket struct {
	DkgGroup *GroupInfo `protobuf:"bytes,1,opt,name=dkg_group,json=dkgGroup,proto3" json:"dkg_group,omitempty"`
	IsLeader bool       `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// timeout as parsed by Golang's time.ParseDuration method.
	Timeout              string   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitDKGPacket) Reset()         { *m = InitDKGPacket{} }
func (m *InitDKGPacket) String() string { return proto.CompactTextString(m) }
func (*InitDKGPacket) ProtoMessage()    {}
func (*InitDKGPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{0}
}
func (m *InitDKGPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitDKGPacket.Unmarshal(m, b)
}
func (m *InitDKGPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitDKGPacket.Marshal(b, m, deterministic)
}
func (dst *InitDKGPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitDKGPacket.Merge(dst, src)
}
func (m *InitDKGPacket) XXX_Size() int {
	return xxx_messageInfo_InitDKGPacket.Size(m)
}
func (m *InitDKGPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_InitDKGPacket.DiscardUnknown(m)
}

var xxx_messageInfo_InitDKGPacket proto.InternalMessageInfo

func (m *InitDKGPacket) GetDkgGroup() *GroupInfo {
	if m != nil {
		return m.DkgGroup
	}
	return nil
}

func (m *InitDKGPacket) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *InitDKGPacket) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

// ReshareRequest contains references to the old and new group to perform the
// resharing protocol.
type InitResharePacket struct {
	// Old group that needs to issue the shares for the new group
	// NOTE: It can be empty / nil. In that case, the drand node will try to
	// load the group he belongs to at the moment, if any, and use it as the old
	// group.
	Old      *GroupInfo `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New      *GroupInfo `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	IsLeader bool       `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// timeout as parsed by Golang's time.ParseDuration method.
	Timeout              string   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResharePacket) Reset()         { *m = InitResharePacket{} }
func (m *InitResharePacket) String() string { return proto.CompactTextString(m) }
func (*InitResharePacket) ProtoMessage()    {}
func (*InitResharePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{1}
}
func (m *InitResharePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResharePacket.Unmarshal(m, b)
}
func (m *InitResharePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResharePacket.Marshal(b, m, deterministic)
}
func (dst *InitResharePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResharePacket.Merge(dst, src)
}
func (m *InitResharePacket) XXX_Size() int {
	return xxx_messageInfo_InitResharePacket.Size(m)
}
func (m *InitResharePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResharePacket.DiscardUnknown(m)
}

var xxx_messageInfo_InitResharePacket proto.InternalMessageInfo

func (m *InitResharePacket) GetOld() *GroupInfo {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *InitResharePacket) GetNew() *GroupInfo {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *InitResharePacket) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *InitResharePacket) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type GroupInfo struct {
	// Types that are valid to be assigned to Location:
	//	*GroupInfo_Path
	//	*GroupInfo_Url
	Location             isGroupInfo_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{2}
}
func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (dst *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(dst, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

type isGroupInfo_Location interface {
	isGroupInfo_Location()
}

type GroupInfo_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type GroupInfo_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*GroupInfo_Path) isGroupInfo_Location() {}

func (*GroupInfo_Url) isGroupInfo_Location() {}

func (m *GroupInfo) GetLocation() isGroupInfo_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GroupInfo) GetPath() string {
	if x, ok := m.GetLocation().(*GroupInfo_Path); ok {
		return x.Path
	}
	return ""
}

func (m *GroupInfo) GetUrl() string {
	if x, ok := m.GetLocation().(*GroupInfo_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GroupInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GroupInfo_OneofMarshaler, _GroupInfo_OneofUnmarshaler, _GroupInfo_OneofSizer, []interface{}{
		(*GroupInfo_Path)(nil),
		(*GroupInfo_Url)(nil),
	}
}

func _GroupInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GroupInfo)
	// location
	switch x := m.Location.(type) {
	case *GroupInfo_Path:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Path)
	case *GroupInfo_Url:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Url)
	case nil:
	default:
		return fmt.Errorf("GroupInfo.Location has unexpected type %T", x)
	}
	return nil
}

func _GroupInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GroupInfo)
	switch tag {
	case 1: // location.path
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &GroupInfo_Path{x}
		return true, err
	case 2: // location.url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &GroupInfo_Url{x}
		return true, err
	default:
		return false, nil
	}
}

func _GroupInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GroupInfo)
	// location
	switch x := m.Location.(type) {
	case *GroupInfo_Path:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Path)))
		n += len(x.Path)
	case *GroupInfo_Url:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Url)))
		n += len(x.Url)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ShareRequest requests the private share of a drand node
type ShareRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareRequest) Reset()         { *m = ShareRequest{} }
func (m *ShareRequest) String() string { return proto.CompactTextString(m) }
func (*ShareRequest) ProtoMessage()    {}
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{3}
}
func (m *ShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareRequest.Unmarshal(m, b)
}
func (m *ShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareRequest.Marshal(b, m, deterministic)
}
func (dst *ShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareRequest.Merge(dst, src)
}
func (m *ShareRequest) XXX_Size() int {
	return xxx_messageInfo_ShareRequest.Size(m)
}
func (m *ShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareRequest proto.InternalMessageInfo

// ShareResponse holds the private share of a drand node
type ShareResponse struct {
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Share                []byte   `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareResponse) Reset()         { *m = ShareResponse{} }
func (m *ShareResponse) String() string { return proto.CompactTextString(m) }
func (*ShareResponse) ProtoMessage()    {}
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{4}
}
func (m *ShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareResponse.Unmarshal(m, b)
}
func (m *ShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareResponse.Marshal(b, m, deterministic)
}
func (dst *ShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareResponse.Merge(dst, src)
}
func (m *ShareResponse) XXX_Size() int {
	return xxx_messageInfo_ShareResponse.Size(m)
}
func (m *ShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareResponse proto.InternalMessageInfo

func (m *ShareResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ShareResponse) GetShare() []byte {
	if m != nil {
		return m.Share
	}
	return nil
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{5}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{6}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

// PublicKeyRequest requests the public key of a drand node
type PublicKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyRequest) Reset()         { *m = PublicKeyRequest{} }
func (m *PublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyRequest) ProtoMessage()    {}
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{7}
}
func (m *PublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyRequest.Unmarshal(m, b)
}
func (m *PublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyRequest.Marshal(b, m, deterministic)
}
func (dst *PublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyRequest.Merge(dst, src)
}
func (m *PublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PublicKeyRequest.Size(m)
}
func (m *PublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyRequest proto.InternalMessageInfo

// PublicKeyResponse holds the public key of a drand node
type PublicKeyResponse struct {
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyResponse) Reset()         { *m = PublicKeyResponse{} }
func (m *PublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PublicKeyResponse) ProtoMessage()    {}
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{8}
}
func (m *PublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyResponse.Unmarshal(m, b)
}
func (m *PublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyResponse.Marshal(b, m, deterministic)
}
func (dst *PublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyResponse.Merge(dst, src)
}
func (m *PublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PublicKeyResponse.Size(m)
}
func (m *PublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyResponse proto.InternalMessageInfo

func (m *PublicKeyResponse) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

// PrivateKeyRequest requests the private key of a drand node
type PrivateKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyRequest) Reset()         { *m = PrivateKeyRequest{} }
func (m *PrivateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyRequest) ProtoMessage()    {}
func (*PrivateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{9}
}
func (m *PrivateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyRequest.Unmarshal(m, b)
}
func (m *PrivateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyRequest.Marshal(b, m, deterministic)
}
func (dst *PrivateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyRequest.Merge(dst, src)
}
func (m *PrivateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyRequest.Size(m)
}
func (m *PrivateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyRequest proto.InternalMessageInfo

// PrivateKeyResponse holds the private key of a drand node
type PrivateKeyResponse struct {
	PriKey               []byte   `protobuf:"bytes,2,opt,name=priKey,proto3" json:"priKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyResponse) Reset()         { *m = PrivateKeyResponse{} }
func (m *PrivateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyResponse) ProtoMessage()    {}
func (*PrivateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{10}
}
func (m *PrivateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyResponse.Unmarshal(m, b)
}
func (m *PrivateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyResponse.Marshal(b, m, deterministic)
}
func (dst *PrivateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyResponse.Merge(dst, src)
}
func (m *PrivateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyResponse.Size(m)
}
func (m *PrivateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyResponse proto.InternalMessageInfo

func (m *PrivateKeyResponse) GetPriKey() []byte {
	if m != nil {
		return m.PriKey
	}
	return nil
}

// CokeyRequest requests the collective key of a drand node
type CokeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CokeyRequest) Reset()         { *m = CokeyRequest{} }
func (m *CokeyRequest) String() string { return proto.CompactTextString(m) }
func (*CokeyRequest) ProtoMessage()    {}
func (*CokeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{11}
}
func (m *CokeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CokeyRequest.Unmarshal(m, b)
}
func (m *CokeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CokeyRequest.Marshal(b, m, deterministic)
}
func (dst *CokeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CokeyRequest.Merge(dst, src)
}
func (m *CokeyRequest) XXX_Size() int {
	return xxx_messageInfo_CokeyRequest.Size(m)
}
func (m *CokeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CokeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CokeyRequest proto.InternalMessageInfo

// CokeyResponse holds the collective key of a drand node
type CokeyResponse struct {
	CoKey                []byte   `protobuf:"bytes,2,opt,name=coKey,proto3" json:"coKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CokeyResponse) Reset()         { *m = CokeyResponse{} }
func (m *CokeyResponse) String() string { return proto.CompactTextString(m) }
func (*CokeyResponse) ProtoMessage()    {}
func (*CokeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{12}
}
func (m *CokeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CokeyResponse.Unmarshal(m, b)
}
func (m *CokeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CokeyResponse.Marshal(b, m, deterministic)
}
func (dst *CokeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CokeyResponse.Merge(dst, src)
}
func (m *CokeyResponse) XXX_Size() int {
	return xxx_messageInfo_CokeyResponse.Size(m)
}
func (m *CokeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CokeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CokeyResponse proto.InternalMessageInfo

func (m *CokeyResponse) GetCoKey() []byte {
	if m != nil {
		return m.CoKey
	}
	return nil
}

type GroupTOMLRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTOMLRequest) Reset()         { *m = GroupTOMLRequest{} }
func (m *GroupTOMLRequest) String() string { return proto.CompactTextString(m) }
func (*GroupTOMLRequest) ProtoMessage()    {}
func (*GroupTOMLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{13}
}
func (m *GroupTOMLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTOMLRequest.Unmarshal(m, b)
}
func (m *GroupTOMLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTOMLRequest.Marshal(b, m, deterministic)
}
func (dst *GroupTOMLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTOMLRequest.Merge(dst, src)
}
func (m *GroupTOMLRequest) XXX_Size() int {
	return xxx_messageInfo_GroupTOMLRequest.Size(m)
}
func (m *GroupTOMLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTOMLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTOMLRequest proto.InternalMessageInfo

type GroupTOMLResponse struct {
	// TOML-encoded group file
	GroupToml            string   `protobuf:"bytes,1,opt,name=group_toml,json=groupToml,proto3" json:"group_toml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTOMLResponse) Reset()         { *m = GroupTOMLResponse{} }
func (m *GroupTOMLResponse) String() string { return proto.CompactTextString(m) }
func (*GroupTOMLResponse) ProtoMessage()    {}
func (*GroupTOMLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_86528edb8dc0c133, []int{14}
}
func (m *GroupTOMLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTOMLResponse.Unmarshal(m, b)
}
func (m *GroupTOMLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTOMLResponse.Marshal(b, m, deterministic)
}
func (dst *GroupTOMLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTOMLResponse.Merge(dst, src)
}
func (m *GroupTOMLResponse) XXX_Size() int {
	return xxx_messageInfo_GroupTOMLResponse.Size(m)
}
func (m *GroupTOMLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTOMLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTOMLResponse proto.InternalMessageInfo

func (m *GroupTOMLResponse) GetGroupToml() string {
	if m != nil {
		return m.GroupToml
	}
	return ""
}

func init() {
	proto.RegisterType((*InitDKGPacket)(nil), "drand.InitDKGPacket")
	proto.RegisterType((*InitResharePacket)(nil), "drand.InitResharePacket")
	proto.RegisterType((*GroupInfo)(nil), "drand.GroupInfo")
	proto.RegisterType((*ShareRequest)(nil), "drand.ShareRequest")
	proto.RegisterType((*ShareResponse)(nil), "drand.ShareResponse")
	proto.RegisterType((*Ping)(nil), "drand.Ping")
	proto.RegisterType((*Pong)(nil), "drand.Pong")
	proto.RegisterType((*PublicKeyRequest)(nil), "drand.PublicKeyRequest")
	proto.RegisterType((*PublicKeyResponse)(nil), "drand.PublicKeyResponse")
	proto.RegisterType((*PrivateKeyRequest)(nil), "drand.PrivateKeyRequest")
	proto.RegisterType((*PrivateKeyResponse)(nil), "drand.PrivateKeyResponse")
	proto.RegisterType((*CokeyRequest)(nil), "drand.CokeyRequest")
	proto.RegisterType((*CokeyResponse)(nil), "drand.CokeyResponse")
	proto.RegisterType((*GroupTOMLRequest)(nil), "drand.GroupTOMLRequest")
	proto.RegisterType((*GroupTOMLResponse)(nil), "drand.GroupTOMLResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(ctx context.Context, in *InitDKGPacket, opts ...grpc.CallOption) (*Empty, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(ctx context.Context, in *InitResharePacket, opts ...grpc.CallOption) (*Empty, error)
	// Share returns the current private share used by the node
	Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	// PublicKey returns the longterm public key of the drand node
	PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	// PrivateKey returns the longterm private key of the drand node
	PrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error)
	// CollectiveKey returns the distributed public key used by the node
	CollectiveKey(ctx context.Context, in *CokeyRequest, opts ...grpc.CallOption) (*CokeyResponse, error)
	// GroupFile returns the TOML-encoded group file
	// similar to public.Group method but needed for ease of use of the
	// control functionalities
	GroupFile(ctx context.Context, in *GroupTOMLRequest, opts ...grpc.CallOption) (*GroupTOMLResponse, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/drand.Control/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitDKG(ctx context.Context, in *InitDKGPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/drand.Control/InitDKG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitReshare(ctx context.Context, in *InitResharePacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/drand.Control/InitReshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/Share", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) PrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error) {
	out := new(PrivateKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/PrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CollectiveKey(ctx context.Context, in *CokeyRequest, opts ...grpc.CallOption) (*CokeyResponse, error) {
	out := new(CokeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/CollectiveKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GroupFile(ctx context.Context, in *GroupTOMLRequest, opts ...grpc.CallOption) (*GroupTOMLResponse, error) {
	out := new(GroupTOMLResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/GroupFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(context.Context, *Ping) (*Pong, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(context.Context, *InitDKGPacket) (*Empty, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(context.Context, *InitResharePacket) (*Empty, error)
	// Share returns the current private share used by the node
	Share(context.Context, *ShareRequest) (*ShareResponse, error)
	// PublicKey returns the longterm public key of the drand node
	PublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error)
	// PrivateKey returns the longterm private key of the drand node
	PrivateKey(context.Context, *PrivateKeyRequest) (*PrivateKeyResponse, error)
	// CollectiveKey returns the distributed public key used by the node
	CollectiveKey(context.Context, *CokeyRequest) (*CokeyResponse, error)
	// GroupFile returns the TOML-encoded group file
	// similar to public.Group method but needed for ease of use of the
	// control functionalities
	GroupFile(context.Context, *GroupTOMLRequest) (*GroupTOMLResponse, error)
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitDKGPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/InitDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitDKG(ctx, req.(*InitDKGPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitReshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitResharePacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitReshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/InitReshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitReshare(ctx, req.(*InitResharePacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Share_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Share(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/Share",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Share(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PublicKey(ctx, req.(*PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_PrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PrivateKey(ctx, req.(*PrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CollectiveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CokeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CollectiveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/CollectiveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CollectiveKey(ctx, req.(*CokeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GroupFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupTOMLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GroupFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/GroupFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GroupFile(ctx, req.(*GroupTOMLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drand.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _Control_PingPong_Handler,
		},
		{
			MethodName: "InitDKG",
			Handler:    _Control_InitDKG_Handler,
		},
		{
			MethodName: "InitReshare",
			Handler:    _Control_InitReshare_Handler,
		},
		{
			MethodName: "Share",
			Handler:    _Control_Share_Handler,
		},
		{
			MethodName: "PublicKey",
			Handler:    _Control_PublicKey_Handler,
		},
		{
			MethodName: "PrivateKey",
			Handler:    _Control_PrivateKey_Handler,
		},
		{
			MethodName: "CollectiveKey",
			Handler:    _Control_CollectiveKey_Handler,
		},
		{
			MethodName: "GroupFile",
			Handler:    _Control_GroupFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drand/control.proto",
}

func init() { proto.RegisterFile("drand/control.proto", fileDescriptor_control_86528edb8dc0c133) }

var fileDescriptor_control_86528edb8dc0c133 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x05, 0xd9, 0x5d, 0xe8, 0x05, 0xcc, 0x32, 0x10, 0xad, 0x35, 0x26, 0xa4, 0xc9, 0x2a, 0x89,
	0x0a, 0x09, 0x9a, 0xf8, 0xa0, 0x0f, 0xba, 0xa8, 0xeb, 0x86, 0x35, 0x92, 0xba, 0x4f, 0xbe, 0x90,
	0xd2, 0xce, 0x96, 0x09, 0xa5, 0x53, 0xdb, 0xe9, 0xae, 0xfc, 0x0d, 0x7f, 0x9d, 0x3f, 0xc7, 0xcc,
	0x9d, 0xa1, 0xb4, 0xcb, 0xee, 0x13, 0x39, 0xe7, 0xf6, 0x7e, 0x9c, 0x7b, 0x2e, 0x03, 0x5d, 0x3f,
	0x71, 0x23, 0x7f, 0xe4, 0xf1, 0x48, 0x24, 0x3c, 0x1c, 0xc6, 0x09, 0x17, 0x9c, 0x1c, 0x22, 0x69,
	0x75, 0x54, 0x8c, 0xae, 0x63, 0xb1, 0x51, 0x11, 0x3b, 0x83, 0xf6, 0x79, 0xc4, 0xc4, 0xe7, 0xe9,
	0xd9, 0xcc, 0xf5, 0x56, 0x54, 0x90, 0xd7, 0x60, 0xf8, 0xab, 0x60, 0x1e, 0x24, 0x3c, 0x8b, 0xcd,
	0x6a, 0xbf, 0x3a, 0x68, 0x8e, 0x8f, 0x87, 0x98, 0x37, 0x3c, 0x93, 0xdc, 0x79, 0x74, 0xc5, 0x9d,
	0x86, 0xbf, 0x0a, 0x10, 0x91, 0xa7, 0x60, 0xb0, 0x74, 0x1e, 0x52, 0xd7, 0xa7, 0x89, 0xf9, 0xa0,
	0x5f, 0x1d, 0x34, 0x9c, 0x06, 0x4b, 0x2f, 0x10, 0x13, 0x13, 0xea, 0x82, 0xad, 0x29, 0xcf, 0x84,
	0x59, 0xeb, 0x57, 0x07, 0x86, 0xb3, 0x85, 0xf6, 0xdf, 0x2a, 0x74, 0x64, 0x5f, 0x87, 0xa6, 0x4b,
	0x37, 0xa1, 0xba, 0xb7, 0x0d, 0x35, 0x1e, 0xfa, 0xf7, 0x76, 0x95, 0x41, 0xf9, 0x4d, 0x44, 0x6f,
	0xb0, 0xd5, 0x9d, 0xdf, 0x44, 0xf4, 0xa6, 0x3c, 0x54, 0xed, 0xfe, 0xa1, 0x0e, 0xca, 0x43, 0x7d,
	0x02, 0x23, 0x2f, 0x44, 0x7a, 0x70, 0x10, 0xbb, 0x62, 0x89, 0xc3, 0x18, 0xdf, 0x2a, 0x0e, 0x22,
	0x42, 0xa0, 0x96, 0x25, 0x21, 0x76, 0x97, 0xa4, 0x04, 0xa7, 0x00, 0x8d, 0x90, 0x7b, 0xae, 0x60,
	0x3c, 0xb2, 0x1f, 0x42, 0xeb, 0xa7, 0x14, 0xe4, 0xd0, 0xdf, 0x19, 0x4d, 0x85, 0xfd, 0x1e, 0xda,
	0x1a, 0xa7, 0x31, 0x8f, 0x52, 0x4a, 0x7a, 0x70, 0xc8, 0x22, 0x9f, 0xfe, 0xc1, 0x12, 0x6d, 0x47,
	0x01, 0xc9, 0xe2, 0x1e, 0x70, 0xd8, 0x96, 0xa3, 0x80, 0x7d, 0x04, 0x07, 0x33, 0x16, 0x05, 0xf8,
	0xcb, 0xa3, 0xc0, 0x26, 0x70, 0x3c, 0xcb, 0x16, 0x21, 0xf3, 0xa6, 0x74, 0xb3, 0x6d, 0xf0, 0x12,
	0x3a, 0x05, 0x4e, 0x37, 0x79, 0x04, 0x47, 0x71, 0xb6, 0x98, 0xd2, 0x0d, 0x76, 0x69, 0x39, 0x1a,
	0xd9, 0x5d, 0xe8, 0xcc, 0x12, 0x76, 0xed, 0x0a, 0x5a, 0xa8, 0xf0, 0x0a, 0x48, 0x91, 0x2c, 0x94,
	0x48, 0x58, 0xb1, 0x04, 0x22, 0x29, 0x70, 0xc2, 0x57, 0xbb, 0xec, 0x13, 0x68, 0x6b, 0xbc, 0x13,
	0xe8, 0xf1, 0x5d, 0x9e, 0x02, 0x72, 0x74, 0x5c, 0xed, 0xe5, 0x8f, 0xef, 0x17, 0xdb, 0xd4, 0x31,
	0x74, 0x0a, 0x9c, 0x4e, 0x7f, 0x06, 0x80, 0xa7, 0x37, 0x17, 0x7c, 0x1d, 0xaa, 0xe5, 0x3b, 0x06,
	0x32, 0x97, 0x7c, 0x1d, 0x8e, 0xff, 0xd5, 0xa0, 0x3e, 0x51, 0xa7, 0x4d, 0x9e, 0x43, 0x43, 0xae,
	0x47, 0xae, 0x86, 0x34, 0xf5, 0x21, 0x48, 0xc2, 0xca, 0x81, 0x5c, 0x5a, 0x85, 0x8c, 0xa0, 0xae,
	0x4f, 0x9c, 0xf4, 0x74, 0xa4, 0x74, 0xf2, 0x56, 0x4b, 0xb3, 0x5f, 0xe4, 0xff, 0xc2, 0xae, 0x90,
	0x77, 0xd0, 0x2c, 0xdc, 0x26, 0x31, 0x0b, 0x49, 0xa5, 0x7b, 0xdd, 0x4b, 0x7c, 0x0b, 0x87, 0xe8,
	0x36, 0xe9, 0xea, 0x40, 0xf1, 0x16, 0xac, 0x5e, 0x99, 0x54, 0x82, 0xed, 0x0a, 0xf9, 0x08, 0x46,
	0x6e, 0x21, 0x79, 0xbc, 0x9d, 0xfd, 0x96, 0xd1, 0x96, 0xb9, 0x1f, 0xc8, 0x2b, 0x4c, 0x00, 0x76,
	0x16, 0xe6, 0xf3, 0xee, 0x59, 0x6d, 0x3d, 0xb9, 0x23, 0x92, 0x17, 0xf9, 0x20, 0x9d, 0x0c, 0x43,
	0xea, 0x09, 0x76, 0x8d, 0x75, 0xb6, 0x22, 0x8a, 0x7e, 0xe7, 0x22, 0x4a, 0xa6, 0x2b, 0x11, 0x68,
	0xe6, 0x57, 0x16, 0xd2, 0x5c, 0xc4, 0x6d, 0xcb, 0x73, 0x11, 0x7b, 0xbe, 0xdb, 0x95, 0xd3, 0x17,
	0xbf, 0x4e, 0x02, 0x26, 0x96, 0xd9, 0x62, 0xe8, 0xf1, 0xf5, 0xc8, 0xa7, 0x3e, 0x4b, 0x47, 0xea,
	0xbd, 0xc2, 0x97, 0x6a, 0x91, 0x5d, 0x29, 0xb8, 0x38, 0x42, 0xfc, 0xe6, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0xf4, 0x3a, 0x96, 0xea, 0x04, 0x00, 0x00,
}
