name: "Check Public APIs"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check breakage in public APIs
        run: |
          go install github.com/AnomalRoil/gapi@latest
          gapi .
