name: govulncheck

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}-govulncheck
  cancel-in-progress: true

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.25
          go-package: ./...
